var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/claude/stream/route.js")
R.c("server/chunks/node_modules_formdata-node_lib_esm_fileFromPath_d9268bbb.js")
R.c("server/chunks/[root-of-the-server]__9c913849._.js")
R.c("server/chunks/node_modules_next_7f096d36._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@anthropic-ai_claude-agent-sdk_sdk_mjs_2da8abf1._.js")
R.c("server/chunks/node_modules_zod_v3_f358d7b3._.js")
R.c("server/chunks/ece01_tr46_6f419d3c._.js")
R.c("server/chunks/node_modules_tailwind-merge_dist_bundle-mjs_mjs_c3b2c59f._.js")
R.c("server/chunks/node_modules_4bf87b52._.js")
R.c("server/chunks/apps_web__next-internal_server_app_api_claude_stream_route_actions_f089a656.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/claude/stream/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/apps/web/app/api/claude/stream/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
