// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deploy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deploy">> = Specific
  const handler = {} as typeof import("../../../app/deploy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dns-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dns-setup">> = Specific
  const handler = {} as typeof import("../../../app/docs/dns-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager">> = Specific
  const handler = {} as typeof import("../../../app/manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/photobook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/photobook">> = Specific
  const handler = {} as typeof import("../../../app/photobook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-checks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-checks">> = Specific
  const handler = {} as typeof import("../../../app/test-checks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/claude/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude">> = Specific
  const handler = {} as typeof import("../../../app/api/claude/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/claude/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude/stream">> = Specific
  const handler = {} as typeof import("../../../app/api/claude/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/deploy-subdomain/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deploy-subdomain">> = Specific
  const handler = {} as typeof import("../../../app/api/deploy-subdomain/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deploy">> = Specific
  const handler = {} as typeof import("../../../app/api/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files">> = Specific
  const handler = {} as typeof import("../../../app/api/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/images/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/delete">> = Specific
  const handler = {} as typeof import("../../../app/api/images/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/images/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/list">> = Specific
  const handler = {} as typeof import("../../../app/api/images/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/images/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/images/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/install-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/install-package">> = Specific
  const handler = {} as typeof import("../../../app/api/install-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../../app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/manager/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/manager/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/manager/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager">> = Specific
  const handler = {} as typeof import("../../../app/api/manager/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/manager/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/status">> = Specific
  const handler = {} as typeof import("../../../app/api/manager/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/restart-workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/restart-workspace">> = Specific
  const handler = {} as typeof import("../../../app/api/restart-workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sites/check-availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sites/check-availability">> = Specific
  const handler = {} as typeof import("../../../app/api/sites/check-availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sites/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sites/metadata">> = Specific
  const handler = {} as typeof import("../../../app/api/sites/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test-safety/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-safety">> = Specific
  const handler = {} as typeof import("../../../app/api/test-safety/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhook/deploy/logs/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/deploy/logs/[filename]">> = Specific
  const handler = {} as typeof import("../../../app/api/webhook/deploy/logs/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhook/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/deploy">> = Specific
  const handler = {} as typeof import("../../../app/api/webhook/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
