/**
 * Infrastructure Services Registry
 *
 * Non-site, non-environment services that need tunnel routing and/or
 * internal Caddy host→port mapping.
 *
 * This is the SINGLE SOURCE OF TRUTH for infrastructure service routing.
 * Used by:
 *   - packages/tunnel/src/sync.ts (tunnel ingress rules + Caddyfile.internal generation)
 *   - scripts/maintenance/routing-smoke.sh (health checks)
 *   - E2E routing tests
 *
 * Route types:
 *   "direct"  — cloudflared routes directly to the service port (no Caddy interception)
 *   "caddy"   — cloudflared routes to internal Caddy :8444, which proxies to the service
 *
 * ┌─────────────────────────────────────────────────────────────────┐
 * │  TUNNEL INGRESS                                                │
 * │    direct:  hostname → localhost:{port}                        │
 * │    caddy:   hostname → localhost:8444 → Caddy map → :{port}   │
 * └─────────────────────────────────────────────────────────────────┘
 */

export interface InfrastructureService {
  /** Hostname (e.g. "widget.alive.best") */
  hostname: string
  /** Local port the service listens on */
  port: number
  /** How the tunnel routes to this service */
  routeVia: "direct" | "caddy"
  /** Human-readable name for logs and smoke tests */
  displayName: string
  /** Optional: path to check for health (e.g. "/widget.js", "/health") */
  healthPath?: string
  /** Expected content-type prefix for health check (e.g. "application/javascript") */
  healthContentType?: string
}

/**
 * Infrastructure services — SINGLE SOURCE OF TRUTH
 *
 * When adding a new service:
 * 1. Add entry here
 * 2. Run tunnel sync: `bun run --cwd packages/tunnel sync`
 * 3. Caddyfile.internal is auto-generated by sync
 */
export const INFRASTRUCTURE_SERVICES: readonly InfrastructureService[] = [
  {
    hostname: "widget.alive.best",
    port: 5050,
    routeVia: "direct",
    displayName: "Widget Server",
    healthPath: "/widget.js",
    healthContentType: "application/javascript",
  },
  {
    hostname: "mg.alive.best",
    port: 5090,
    routeVia: "direct",
    displayName: "Manager",
    healthPath: "/",
  },
  {
    hostname: "oc.alive.best",
    port: 18789,
    routeVia: "direct",
    displayName: "OpenClaw",
    healthPath: "/health",
  },
  {
    hostname: "services.alive.best",
    port: 1200,
    routeVia: "direct",
    displayName: "Linkding",
    healthPath: "/",
  },
  {
    hostname: "dl1.alive.best",
    port: 8444,
    routeVia: "caddy",
    displayName: "E2E Test Domain",
  },
  {
    hostname: "infra.alive.best",
    port: 8444,
    routeVia: "caddy",
    displayName: "Infra Placeholder",
  },
] as const
