#!/usr/bin/env bun
/**
 * Generate preview subdomain Caddyfile blocks from existing domain→port mappings
 *
 * This script:
 * 1. Parses the main Caddyfile to extract domain→port mappings
 * 2. Generates corresponding preview subdomain blocks
 * 3. Outputs Caddyfile snippet to stdout (append manually or via script)
 *
 * Example output:
 *   protino-alive-best.preview.terminal.goalive.nl {
 *     reverse_proxy localhost:3357 {
 *       header_up Host localhost
 *     }
 *     header {
 *       -X-Frame-Options
 *       Content-Security-Policy "frame-ancestors https://staging.terminal.goalive.nl https://terminal.goalive.nl"
 *     }
 *     forward_auth https://staging.terminal.goalive.nl/api/auth/preview-guard
 *   }
 */

import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

const CADDYFILE_PATH = "/root/webalive/claude-bridge/Caddyfile"
const PREVIEW_BASE = "preview.terminal.goalive.nl"
const AUTH_ENDPOINT = "https://staging.terminal.goalive.nl/api/auth/preview-guard"

interface DomainMapping {
  domain: string
  port: number
}

/**
 * Parse Caddyfile to extract domain→port mappings
 */
function parseCaddyfile(content: string): DomainMapping[] {
  const mappings: DomainMapping[] = []

  // Regex to match domain blocks with reverse_proxy directives
  // Handles both single domains and comma-separated domains
  const domainBlockRegex = /^([a-zA-Z0-9.-]+(?:,\s*[a-zA-Z0-9.-]+)*)\s*\{[\s\S]*?reverse_proxy\s+localhost:(\d+)/gm

  for (const match of content.matchAll(domainBlockRegex)) {
    const domains = match[1].split(",").map(d => d.trim())
    const port = parseInt(match[2], 10)

    for (const domain of domains) {
      // Skip Claude Bridge itself and non-workspace domains
      if (domain.includes("terminal.goalive.nl") || domain.includes("staging.goalive.nl")) {
        continue
      }

      mappings.push({ domain, port })
    }
  }

  return mappings
}

/**
 * Convert domain to preview subdomain label
 * Examples:
 *   protino.alive.best → protino-alive-best
 *   demo.goalive.nl → demo-goalive-nl
 *
 * Note: Matches domainToPreviewLabel() in apps/web/lib/preview-utils.ts
 */
function domainToLabel(domain: string): string {
  return domain.replace(/\./g, "-")
}

/**
 * Generate preview subdomain block for a workspace
 */
function generatePreviewBlock(mapping: DomainMapping): string {
  const label = domainToLabel(mapping.domain)
  const previewHost = `${label}.${PREVIEW_BASE}`

  return `
${previewHost} {
    reverse_proxy localhost:${mapping.port} {
        header_up Host localhost
    }

    header {
        # Security headers (embeddable variant)
        -X-Frame-Options
        Content-Security-Policy "frame-ancestors https://staging.terminal.goalive.nl https://terminal.goalive.nl"
        X-Content-Type-Options nosniff
        Referrer-Policy strict-origin-when-cross-origin
        -Server
        -X-Powered-By
    }

    # Auth check via forward_auth (direct to localhost to avoid redirect loops)
    forward_auth localhost:8998 {
        uri /api/auth/preview-guard
        copy_headers Cookie
    }
}
`.trimStart()
}

/**
 * Generate complete preview section for Caddyfile
 */
function generatePreviewSection(mappings: DomainMapping[]): string {
  const blocks = mappings.map(generatePreviewBlock).join("\n")

  return `
# ============================================================================
# PREVIEW SUBDOMAINS (AUTO-GENERATED)
# ============================================================================
# This section is auto-generated by scripts/generate-preview-caddyfile.ts
# DO NOT EDIT MANUALLY - Changes will be overwritten
#
# Preview subdomains allow iframe embedding of workspace dev servers
# with proper authentication and security headers.
#
# Format: <workspace-label>.preview.terminal.goalive.nl → localhost:<port>
# Example: protino-alive-best.preview.terminal.goalive.nl → localhost:3357
#
# Features:
# - Host header set to "localhost" for Vite dev server compatibility
# - X-Frame-Options removed to allow iframe embedding
# - CSP frame-ancestors restricts to terminal.goalive.nl domains only
# - forward_auth enforces session authentication at Caddy edge
# ============================================================================

${blocks}
# ============================================================================
# END PREVIEW SUBDOMAINS (AUTO-GENERATED)
# ============================================================================
`.trimStart()
}

/**
 * Main execution
 */
function main() {
  // Check if Caddyfile exists
  if (!existsSync(CADDYFILE_PATH)) {
    console.error(`Error: Caddyfile not found at ${CADDYFILE_PATH}`)
    process.exit(1)
  }

  // Read and parse Caddyfile
  const content = readFileSync(CADDYFILE_PATH, "utf-8")
  const mappings = parseCaddyfile(content)

  if (mappings.length === 0) {
    console.error("Error: No domain→port mappings found in Caddyfile")
    process.exit(1)
  }

  console.error(`Found ${mappings.length} workspace domains`)

  // Generate preview section
  const previewSection = generatePreviewSection(mappings)

  // Output to stdout (can be piped or redirected)
  console.log(previewSection)

  console.error("\n✓ Preview Caddyfile blocks generated successfully")
  console.error("To append to Caddyfile, run:")
  console.error(`  bun run ${__filename} >> ${CADDYFILE_PATH}`)
  console.error("Then reload Caddy:")
  console.error("  systemctl reload caddy")
}

main()
