/**
 * Generates nav_script_gen.go from @webalive/shared PREVIEW_MESSAGES constants.
 *
 * This is the single source of truth for postMessage types used in the
 * navigation sync script injected by the Go preview-proxy. Without this,
 * the Go string constant can silently drift from the TypeScript constants,
 * causing the preview loading overlay to never dismiss.
 *
 * Run: bun apps/preview-proxy/generate-nav-script.ts
 * Called automatically by: bun run --cwd apps/preview-proxy generate
 */

// Import directly from constants source to avoid triggering server config loading
// via the @webalive/shared barrel export.
import { PREVIEW_MESSAGES } from "../../packages/shared/src/constants"
import { writeFileSync } from "fs"
import { join } from "path"

const NAV = PREVIEW_MESSAGES.NAVIGATION
const NAV_START = PREVIEW_MESSAGES.NAVIGATION_START

// The script is injected after <head> in HTML responses.
// It must run before any framework JS to capture the initial navigation.
const script = `<script>
(function() {
  if (window.parent === window) return;
  function sendStart() {
    window.parent.postMessage({ type: '${NAV_START}' }, '*');
  }
  function sendPath() {
    window.parent.postMessage({ type: '${NAV}', path: location.pathname }, '*');
  }
  sendPath();
  var origPush = history.pushState, origReplace = history.replaceState;
  history.pushState = function() {
    sendStart();
    origPush.apply(this, arguments);
    sendPath();
  };
  history.replaceState = function() {
    sendStart();
    origReplace.apply(this, arguments);
    sendPath();
  };
  window.addEventListener('popstate', function() { sendStart(); sendPath(); });
  document.addEventListener('click', function(e) {
    var a = e.target.closest('a[href]');
    if (a && a.href && !a.target && a.origin === location.origin) {
      sendStart();
    }
  }, true);
  window.addEventListener('beforeunload', sendStart);
})();
</script>`

// Escape backticks for Go raw string literal
const escaped = script.replace(/`/g, '` + "`" + `')

const goFile = `// Code generated by generate-nav-script.ts — DO NOT EDIT.
// Source of truth: @webalive/shared PREVIEW_MESSAGES constants.
//
// NAVIGATION = "${NAV}"
// NAVIGATION_START = "${NAV_START}"

package main

// navScript is injected into HTML responses to sync iframe navigation
// with the parent Alive chat UI via postMessage.
const navScript = \`${escaped}\`
`

const outPath = join(import.meta.dir, "nav_script_gen.go")
writeFileSync(outPath, goFile)
console.log(`[generate-nav-script] wrote ${outPath}`)
console.log(`[generate-nav-script] NAVIGATION = "${NAV}"`)
console.log(`[generate-nav-script] NAVIGATION_START = "${NAV_START}"`)
