// Code generated by generate-nav-script.ts — DO NOT EDIT.
// Source of truth: @webalive/shared PREVIEW_MESSAGES constants.
//
// NAVIGATION = "preview-navigation"
// NAVIGATION_START = "preview-navigation-start"

package main

// navScript is injected into HTML responses to sync iframe navigation
// with the parent Alive chat UI via postMessage.
const navScript = `<script>
(function() {
  if (window.parent === window) return;
  function sendStart() {
    window.parent.postMessage({ type: 'preview-navigation-start' }, '*');
  }
  function sendPath() {
    window.parent.postMessage({ type: 'preview-navigation', path: location.pathname }, '*');
  }
  sendPath();
  var origPush = history.pushState, origReplace = history.replaceState;
  history.pushState = function() {
    sendStart();
    origPush.apply(this, arguments);
    sendPath();
  };
  history.replaceState = function() {
    sendStart();
    origReplace.apply(this, arguments);
    sendPath();
  };
  window.addEventListener('popstate', function() { sendStart(); sendPath(); });
  document.addEventListener('click', function(e) {
    var a = e.target.closest('a[href]');
    if (a && a.href && !a.target && a.origin === location.origin) {
      sendStart();
    }
  }, true);
  window.addEventListener('beforeunload', sendStart);
})();
</script>`
