import { randomUUID } from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import * as Sentry from "@sentry/nextjs"
import type { NextRequest } from "next/server"
import { getSessionUser } from "@/features/auth/lib/auth"
import { structuredErrorResponse } from "@/lib/api/responses"
import { ErrorCodes } from "@/lib/error-codes"

const LOG_DIR = path.join(process.cwd(), "../../logs")
const DEPLOY_LOG_FILENAME_PATTERN = /^deploy-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}(?:-\d+)?Z\.log$/

/**
 * GET endpoint to view a specific deployment log
 * Access: /api/webhook/deploy/logs/deploy-2025-01-15T10-30-00.log
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ filename: string }> },
) {
  const requestId = randomUUID()

  try {
    const user = await getSessionUser()
    if (!user) {
      return structuredErrorResponse(ErrorCodes.NO_SESSION, { status: 401, details: { requestId } })
    }
    if (!user.isSuperadmin) {
      return structuredErrorResponse(ErrorCodes.FORBIDDEN, { status: 403, details: { requestId } })
    }

    const { filename } = await params

    // Security: only allow reading deploy-*.log files generated by the webhook route
    if (!DEPLOY_LOG_FILENAME_PATTERN.test(filename)) {
      return structuredErrorResponse(ErrorCodes.INVALID_REQUEST, { status: 400, details: { requestId } })
    }

    const logPath = path.join(LOG_DIR, filename)

    // Check if file exists
    if (!fs.existsSync(logPath)) {
      return structuredErrorResponse(ErrorCodes.FILE_READ_ERROR, { status: 404, details: { requestId } })
    }

    // Read log content
    const content = fs.readFileSync(logPath, "utf-8")

    // Return as plain text
    return new Response(content, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
      },
    })
  } catch (error) {
    console.error("[WEBHOOK LOGS] Error:", error)
    Sentry.captureException(error)
    return structuredErrorResponse(ErrorCodes.FILE_READ_ERROR, {
      status: 500,
      details: { requestId, exception: error instanceof Error ? error.message : "Unknown error" },
    })
  }
}
